2023-03-07 17:52:25,026 p=4067019 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 17:52:25,026 p=4067019 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 17:52:25,029 p=4067019 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 17:52:25,081 p=4067019 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:52:25,926 p=4067019 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:52:25,926 p=4067019 u=th n=ansible | ok: [localhost]
2023-03-07 17:52:26,734 p=4067019 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:52:26,735 p=4067019 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/bin/helm repo add argo-cd https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: looks like \"https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd\" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd/index.yaml : 404 Not Found\n", "stderr": "Error: looks like \"https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd\" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd/index.yaml : 404 Not Found\n", "stderr_lines": ["Error: looks like \"https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd\" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd/index.yaml : 404 Not Found"], "stdout": "", "stdout_lines": []}
2023-03-07 17:52:26,738 p=4067019 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-07 17:52:26,738 p=4067019 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:52:26,738 p=4067019 u=th n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-07 17:55:39,811 p=4095300 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 17:55:39,811 p=4095300 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 17:55:39,814 p=4095300 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 17:55:39,867 p=4095300 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:55:40,707 p=4095300 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:55:40,707 p=4095300 u=th n=ansible | ok: [localhost]
2023-03-07 17:55:41,349 p=4095300 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:55:41,349 p=4095300 u=th n=ansible | changed: [localhost]
2023-03-07 17:55:41,383 p=4095300 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 17:55:41,383 p=4095300 u=th n=ansible | localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-07 18:00:02,109 p=4133425 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 18:00:02,109 p=4133425 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 18:00:02,112 p=4133425 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 18:00:02,173 p=4133425 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:04,007 p=4133425 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:04,008 p=4133425 u=th n=ansible | ok: [localhost]
2023-03-07 18:00:04,336 p=4133425 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:04,336 p=4133425 u=th n=ansible | ok: [localhost]
2023-03-07 18:00:04,618 p=4133425 u=th n=ansible | TASK [Install argo-CD] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:04,618 p=4133425 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "release_state is present but all of the following are missing: chart_ref"}
2023-03-07 18:00:04,621 p=4133425 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-07 18:00:04,621 p=4133425 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:04,621 p=4133425 u=th n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-07 18:00:19,611 p=4136118 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 18:00:19,611 p=4136118 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 18:00:19,614 p=4136118 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 18:00:19,667 p=4136118 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:20,541 p=4136118 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:20,542 p=4136118 u=th n=ansible | ok: [localhost]
2023-03-07 18:00:20,876 p=4136118 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:20,876 p=4136118 u=th n=ansible | ok: [localhost]
2023-03-07 18:00:38,830 p=4136118 u=th n=ansible | TASK [Install argo-CD] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:38,831 p=4136118 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/bin/helm upgrade -i --reset-values argo-cd argo-cd/argo-cd", "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"argo-cd\" does not exist. Installing it now.\n\nstderr: Error: create: failed to create: namespaces \"argo-cd\" not found\n", "stderr": "Error: create: failed to create: namespaces \"argo-cd\" not found\n", "stderr_lines": ["Error: create: failed to create: namespaces \"argo-cd\" not found"], "stdout": "Release \"argo-cd\" does not exist. Installing it now.\n", "stdout_lines": ["Release \"argo-cd\" does not exist. Installing it now."]}
2023-03-07 18:00:38,834 p=4136118 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-07 18:00:38,834 p=4136118 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:00:38,834 p=4136118 u=th n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-07 18:02:33,047 p=4155494 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 18:02:33,047 p=4155494 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 18:02:33,050 p=4155494 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 18:02:33,111 p=4155494 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:02:33,989 p=4155494 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:02:33,990 p=4155494 u=th n=ansible | ok: [localhost]
2023-03-07 18:02:34,318 p=4155494 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:02:34,318 p=4155494 u=th n=ansible | ok: [localhost]
2023-03-07 18:02:34,830 p=4155494 u=th n=ansible | TASK [create namespace] ****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:02:34,830 p=4155494 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (kubernetes) on eos-precision's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
2023-03-07 18:02:34,833 p=4155494 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-07 18:02:34,833 p=4155494 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:02:34,833 p=4155494 u=th n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-07 18:05:34,990 p=4182032 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 18:05:34,990 p=4182032 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 18:05:34,993 p=4182032 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 18:05:35,048 p=4182032 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:05:35,980 p=4182032 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:05:35,981 p=4182032 u=th n=ansible | ok: [localhost]
2023-03-07 18:05:36,306 p=4182032 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:05:36,306 p=4182032 u=th n=ansible | ok: [localhost]
2023-03-07 18:05:44,845 p=4182032 u=th n=ansible | TASK [create namespace] ****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:05:44,845 p=4182032 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create object: The `items` field in the body must be populated when calling methods on a ResourceList"}
2023-03-07 18:05:44,848 p=4182032 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-07 18:05:44,848 p=4182032 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:05:44,848 p=4182032 u=th n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-07 18:06:58,664 p=401 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-07 18:06:58,665 p=401 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-07 18:06:58,667 p=401 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-07 18:06:58,721 p=401 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:06:59,553 p=401 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:06:59,554 p=401 u=th n=ansible | ok: [localhost]
2023-03-07 18:06:59,875 p=401 u=th n=ansible | TASK [add-helm-repo] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:06:59,875 p=401 u=th n=ansible | ok: [localhost]
2023-03-07 18:07:01,555 p=401 u=th n=ansible | TASK [create namespace] ****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:07:01,555 p=401 u=th n=ansible | changed: [localhost]
2023-03-07 18:07:28,840 p=401 u=th n=ansible | TASK [Install argo-CD] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:07:28,840 p=401 u=th n=ansible | changed: [localhost]
2023-03-07 18:07:28,865 p=401 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-07 18:07:28,865 p=401 u=th n=ansible | localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2023-03-08 08:47:18,099 p=3601510 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-08 08:47:18,099 p=3601510 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-08 08:47:18,102 p=3601510 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-08 08:47:18,143 p=3601510 u=th n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  could not find expected ':'

The error appears to be in '/home/th/dev/ansible-argoCD/playbooks/deploy_helm.yml': line 26, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        namespace: "{{ helm_release_name }}"
        chart_ref:"{{ helm_release_name }}"/argo-cd
^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2023-03-08 08:47:33,298 p=3603705 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-08 08:47:33,298 p=3603705 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-08 08:47:33,301 p=3603705 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-08 08:47:33,339 p=3603705 u=th n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/home/th/dev/ansible-argoCD/playbooks/deploy_helm.yml': line 25, column 45, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        namespace: "{{ helm_release_name }}"
        chart_ref: "{{ helm_release_name }}"/argo-cd
                                            ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

2023-03-08 08:47:46,172 p=3605582 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-08 08:47:46,172 p=3605582 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-08 08:47:46,175 p=3605582 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-08 08:47:46,236 p=3605582 u=th n=ansible | ERROR! couldn't resolve module/action 'kubernetes.core."helm_repository'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/th/dev/ansible-argoCD/playbooks/deploy_helm.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Helm repo add
      ^ here

2023-03-08 08:48:02,673 p=3607979 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-08 08:48:02,673 p=3607979 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-08 08:48:02,676 p=3607979 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-08 08:48:02,733 p=3607979 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:48:03,648 p=3607979 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:48:03,648 p=3607979 u=th n=ansible | ok: [localhost]
2023-03-08 08:48:03,964 p=3607979 u=th n=ansible | TASK [Helm repo add] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:48:03,964 p=3607979 u=th n=ansible | ok: [localhost]
2023-03-08 08:48:04,703 p=3607979 u=th n=ansible | TASK [create namespace] ****************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:48:04,704 p=3607979 u=th n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'urllib3.exceptions.NewConnectionError'>, <urllib3.connection.HTTPSConnection object at 0x7f9ac70f7010>: Failed to establish a new connection: [Errno 101] Network is unreachable
2023-03-08 08:48:04,704 p=3607979 u=th n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib/python3.10/site-packages/urllib3/connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/lib/python3.10/site-packages/urllib3/util/connection.py\", line 95, in create_connection\n    raise err\n  File \"/usr/lib/python3.10/site-packages/urllib3/util/connection.py\", line 85, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network is unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 386, in _make_request\n    self._validate_conn(conn)\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1042, in _validate_conn\n    conn.connect()\n  File \"/usr/lib/python3.10/site-packages/urllib3/connection.py\", line 358, in connect\n    self.sock = conn = self._new_conn()\n  File \"/usr/lib/python3.10/site-packages/urllib3/connection.py\", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9ac70f7010>: Failed to establish a new connection: [Errno 101] Network is unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/service.py\", line 195, in retrieve\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/client.py\", line 319, in get\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/dynamic/client.py\", line 112, in get\n    return self.request('get', path, **kwargs)\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/dynamic/client.py\", line 55, in inner\n    resp = func(self, *args, **kwargs)\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/dynamic/client.py\", line 270, in request\n    api_response = self.client.call_api(\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/client/rest.py\", line 241, in GET\n    return self.request(\"GET\", url,\n  File \"/home/th/.local/lib/python3.10/site-packages/kubernetes/client/rest.py\", line 214, in request\n    r = self.pool_manager.request(method, url,\n  File \"/usr/lib/python3.10/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/usr/lib/python3.10/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/usr/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/lib/python3.10/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.220.3.67', port=6443): Max retries exceeded with url: /api/v1/namespaces/argo-cd (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ac70f7010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/runner.py\", line 68, in run_module\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/runner.py\", line 112, in perform_action\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/service.py\", line 210, in retrieve\nansible_collections.kubernetes.core.plugins.module_utils.k8s.exceptions.CoreException: Failed to retrieve requested object: HTTPSConnectionPool(host='10.220.3.67', port=6443): Max retries exceeded with url: /api/v1/namespaces/argo-cd (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ac70f7010>: Failed to establish a new connection: [Errno 101] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/th/.ansible/tmp/ansible-tmp-1678261683.9888031-3608351-28900687471673/AnsiballZ_k8s.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/th/.ansible/tmp/ansible-tmp-1678261683.9888031-3608351-28900687471673/AnsiballZ_k8s.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/th/.ansible/tmp/ansible-tmp-1678261683.9888031-3608351-28900687471673/AnsiballZ_k8s.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 479, in <module>\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 473, in main\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/runner.py\", line 85, in run_module\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/core.py\", line 79, in fail_json\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible/module_utils/basic.py\", line 1533, in fail_json\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible/module_utils/basic.py\", line 1506, in _return_formatted\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible/module_utils/common/parameters.py\", line 928, in remove_values\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_atjt2s1f/ansible_kubernetes.core.k8s_payload.zip/ansible/module_utils/common/parameters.py\", line 471, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'urllib3.exceptions.NewConnectionError'>, <urllib3.connection.HTTPSConnection object at 0x7f9ac70f7010>: Failed to establish a new connection: [Errno 101] Network is unreachable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2023-03-08 08:48:04,707 p=3607979 u=th n=ansible | 	to retry, use: --limit @/home/th/dev/ansible-argoCD/config/tmp/retry/deploy_helm.retry

2023-03-08 08:48:04,707 p=3607979 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:48:04,707 p=3607979 u=th n=ansible | localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-03-08 08:57:01,183 p=3687676 u=th n=ansible | [WARNING]: Unable to parse /home/th/dev/ansible-argoCD/inventory/default.ini as an inventory source

2023-03-08 08:57:01,183 p=3687676 u=th n=ansible | [WARNING]: No inventory was parsed, only implicit localhost is available

2023-03-08 08:57:01,186 p=3687676 u=th n=ansible | [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

2023-03-08 08:57:01,251 p=3687676 u=th n=ansible | PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:02,101 p=3687676 u=th n=ansible | TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:02,102 p=3687676 u=th n=ansible | ok: [localhost]
2023-03-08 08:57:02,424 p=3687676 u=th n=ansible | TASK [Helm repo add] *******************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:02,424 p=3687676 u=th n=ansible | ok: [localhost]
2023-03-08 08:57:04,221 p=3687676 u=th n=ansible | TASK [create namespace] ****************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:04,221 p=3687676 u=th n=ansible | ok: [localhost]
2023-03-08 08:57:08,491 p=3687676 u=th n=ansible | TASK [helm install argo-CD] ************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:08,491 p=3687676 u=th n=ansible | [WARNING]: The default idempotency check can fail to report changes in certain cases. Install helm diff >= 3.4.1 for better results.

2023-03-08 08:57:08,491 p=3687676 u=th n=ansible | ok: [localhost]
2023-03-08 08:57:08,517 p=3687676 u=th n=ansible | PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
2023-03-08 08:57:08,517 p=3687676 u=th n=ansible | localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
